language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devops4chiaratti
  api_key:
    secure: fFG4ZtAQ1W05aQ9QxNXX6zQl8GPAT2lywN6ZSi4JcDQdoMm1sxCBljx8dPyqdGObUAsvgYD8kRtcCyywzQk3qKhxtlzj5uqS24eB2KE2CJkw1LlOj/bPeGoVYymw0qY1823plnvZehRbxa2m32Az+7NvwI75HR5XOc7WoXEzxkcUoM6+zrPiHwCoMv/4Y8Qa2OzGg76GJWcJPFY0Sq3R9/eKrgM/+zI0XqrlD1yyMFkKTDRtMQ9juEtCFevxTP8b2/GkaXMZKUJmIF5L8IV83wdjK0+SuBISNwkIL358hHfSrqhKiqHg5IwutG+2Z38NlFOeIYDlPuRskYe6WGhr5Cy59yxsEJf1deW4BIKismAXqwhHRYmgO4BMlNivSnbR/MvbMm4QT/TUgqq3oJjgR3geo38bPcWHj9Vlfvf0x3LiUKAP4DnoIlnrS2/YrWRS8jtrcdHV3f7gFhettCaglu2n/yFnP4gDCeUicR5X8pqZ5Da7cWyI7K4A7yzQX8YUgzYoSPXYzztVS01NEZWZwRZOX3Lr8zUULtdpv2zWi2ImQOyKPuqPv1gNdKR/A2Pdd99ZFxgIpSTpvGaF4OKPjpIQzLVl7nwmxZLG9+dj5A6M5tGFGkZTR4qBk8lwxYoXtMD/BduUT8nxWk1UGvx+OQue8ahFaSXpeIK5aAK03Bk=
